// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0f5MUnA3W1KK1qXmu0wRhvq3MlWAA_fg',
    appId: '1:680857697571:web:cde77e8ed5011936f0e096',
    messagingSenderId: '680857697571',
    projectId: 'flutter-acessibilidade-facil',
    authDomain: 'flutter-acessibilidade-facil.firebaseapp.com',
    storageBucket: 'flutter-acessibilidade-facil.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBCSRxsE7JwQHIQGnH0ZD-ai09c6sjZyg',
    appId: '1:680857697571:android:3b02dddf98455755f0e096',
    messagingSenderId: '680857697571',
    projectId: 'flutter-acessibilidade-facil',
    storageBucket: 'flutter-acessibilidade-facil.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQzdYnxOuZak8ccIzJWnZIbTDzsci36ZA',
    appId: '1:680857697571:ios:fe3060ba2e853c06f0e096',
    messagingSenderId: '680857697571',
    projectId: 'flutter-acessibilidade-facil',
    storageBucket: 'flutter-acessibilidade-facil.appspot.com',
    iosBundleId: 'com.example.acessibilidadeFacil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQzdYnxOuZak8ccIzJWnZIbTDzsci36ZA',
    appId: '1:680857697571:ios:fe3060ba2e853c06f0e096',
    messagingSenderId: '680857697571',
    projectId: 'flutter-acessibilidade-facil',
    storageBucket: 'flutter-acessibilidade-facil.appspot.com',
    iosBundleId: 'com.example.acessibilidadeFacil',
  );
}
